### ISSUE TITLE
primitive type is not supported.

### ISSUE THREAD

**Issue by soranoba** [PHP-DI/PhpDocReader#10]
I hope that the getPropertyClass returns a string (e.g. "int") in the also case of primitive type.
[Here](https://github.com/PHP-DI/PhpDocReader/blob/41f84c5761784f22cbe7604bd581ec26b1e6eb54/src/PhpDocReader/PhpDocReader.php#L89), I think that should be the return `$type`, why is not so?

If this method expect return only class type, I think that it become a library more better, when it is added the another method returns premitive type and object type.

**Comment by mnapoli** [comment]
The main goal for this package (used by PHP-DI) is to resolve type-hints in phpdoc to fully qualified names (i.e. class names with the namespace in it). For the need of PHP-DI the primitive types are not used. I'm not sure how to make it fit into this library without breaking everything.

**Comment by soranoba** [comment]
fmm....
I also think it become a thing that it doesn't meet the purpose of the PHP-DI team, when it take into account until the array of primitive type (or object type).
I look for other libraries along to my purpose.

Thanks for answer.
