### ISSUE TITLE
Support for mixed variable type

### ISSUE THREAD

**Issue by melbings** [PHP-DI/PhpDocReader#12]
Having the following phpdoc...

```php
/**
 * @param mixed $badAnnotation
 */
public function __construct($badAnnotation)
{
    $this->badAnnotation = $badAnnotation;
}
```

... results in an ```AnnotationException``` from ```PhpDocReader/src/PhpDocReader/PhpDocReader.php```:

> The @param annotation for parameter "badAnnotation" of Example::__construct contains a non existent class "mixed". Did you maybe forget to add a "use" statement for this annotation?

It might be preferable to allow annotating fields with "mixed" data types for methods which need to accept any kind of input (e.g., for logging purposes). phpDocumentor [allows "mixed"](http://docs.phpdoc.org/guides/types.html) as well.

**Comment by mnapoli** [comment]
Agreed, that could be added to the list here:

https://github.com/PHP-DI/PhpDocReader/blob/41f84c5761784f22cbe7604bd581ec26b1e6eb54/src/PhpDocReader/PhpDocReader.php#L24-L36

Would you have time to send a pull request with a test case? ([here](https://github.com/PHP-DI/PhpDocReader/blob/41f84c5761784f22cbe7604bd581ec26b1e6eb54/tests/PrimitiveTypesTest.php) I guess)
