### ISSUE TITLE
Do not parse all types of @var

### ISSUE THREAD

**Issue by TuxBoy** [PHP-DI/PhpDocReader#14]
Hi,

I just tried this library to answer a need, I wanted to know if it was wanted the fact that the parser returns the value of @var only if it is an object, not if it is not an example @var string.

Thanks ;)

**Comment by mnapoli** [comment]
Yes, as explained in the readme primitive types are ignored:

> Primitive types (@var string) are ignored (returns null), only valid class names are returned.
