### ISSUE TITLE
PHP 8 - Method ReflectionParameter::getClass() is deprecated

### ISSUE THREAD

**Issue by kocsismate** [PHP-DI/PhpDocReader#19]
Hi Matthieu,

PHP 8 deprecates the `ReflectionParameter::getClass()` method, and suggests the usage of `ReflectionParameter::getType()`. This causes problems (and a slight performance penalty) to PHP-DI.

**Comment by mnapoli** [comment]
There are some commits in https://github.com/PHP-DI/PHP-DI/pull/726 that solve this in PHP-DI, we should apply the same logic here (if anyone is up for a PR).

**Comment by mnapoli** [comment]
I started working on #20 but PHP 8 support is harder than I anticipated.

**Comment by kocsismate** [comment]
Thank you @mnapoli for the fix! I didn't get around implementing this, because I was too busy with PHP 8 before the RCs.
