### ISSUE TITLE
Add run by to readme

### ISSUE THREAD

**Issue by williamdes** [PHP-DI/PhpDocReader#21]
Also run by another DI: https://github.com/woohoolabs/zen

Found on: https://kocsismate.github.io/php-di-container-benchmarks/benchmark.html

Maybe un-list: https://github.com/balihoo/phockito-unit-php-di (no update since 2013)

**Comment by mnapoli** [comment]
Sure feel free to send a pull request. We could also remove that list entirely now that GitHub and Packagist allow to list "dependent" packages.

**Comment by williamdes** [comment]
All done ;p
