### ISSUE TITLE
Support for @return

### ISSUE THREAD

**Issue by kasperg** [PHP-DI/PhpDocReader#5]
Just stumbled upon this project and through it might be useful as some point.

One question: Does the library support `@return`? It does not seem to be mentioned in the documentation.

**Comment by gnugat** [comment]
Looks like someone else took the lead: http://dunglas.fr/2015/02/introducing-propertyinfo-a-php-component-to-find-types-and-doc-of-properties/
I still have to check how it works though.

**Comment by gnugat** [comment]
After a quick look it only provides short and long descriptions (plus the type).
On my way I've found [phpDocumentor/ReflectionDocBlock](https://github.com/phpDocumentor/ReflectionDocBlock) which looks more complete.

**Comment by mnapoli** [comment]
@gnugat I'm interested if you find phpDocumentor/ReflectionDocBlock good enough to replace this package, I'll probably switch to it too then.

**Comment by mnapoli** [comment]
(by good enough I meant it covers all the features that are covered here :)

**Comment by mnapoli** [comment]
Since this repository will not be needed with PHP 8 (and PHP-DI 7), I don't plan on adding more features in there.

I'm cleaning up the issue tracker.

**Comment by RSully** [comment]
It has been a *long* time since I've used PHP, but if it isn't too much to ask for a quick explanation: why isn't this needed in PHP 8 now? I know the language has come a long way!

**Comment by mnapoli** [comment]
@RSully no problem: PHP 8 (and actually PHP 7.2 too) supports return types, as well as putting types basically everywhere.

That means that this package isn't really needed anymore as we can read types from the code instead of the phpdoc.

**Comment by RSully** [comment]
Gotcha, are those enforced, or optional now? Last I remember about PHP typing it was all optional and so a lot of code bases still used `@return` style comments and/or hadn't updated yet. 

I know in the Python world where I'm more familiar, which has been making a similar slow transition, it's even more of a mess and not enforced.

**Comment by mnapoli** [comment]
Those return types are checked at runtime, if that's what you mean.

But developers can choose to use them, or not. In the open-source world, nowadays it's very widespread. If you had to work with a legacy PHP app that's unlikely that you'd find them though.

I recommend reading https://stitcher.io/blog/new-in-php-8 too if you're interested to learn what's coming up in PHP 8.
