### ISSUE TITLE
Unclear statement

### ISSUE THREAD

**Issue by thebigb** [PHP-DI/PhpDocReader#8]
@mnapoli, do you happen to know what the purpose of [PhpDocReader.php#L245](https://github.com/PHP-DI/PhpDocReader/blob/master/src/PhpDocReader/PhpDocReader.php#L245) is? It is not covered by the unit tests, and I can't really figure out what it's supposed to do. Could be legacy code?

**Comment by mnapoli** [comment]
Yes I honestly have no idea ;) It could be legacy code indeed, I'm not sure if it's worth removing and risk a break or not.

**Comment by thebigb** [comment]
I think I figured it out. 

The only place where `'__NAMESPACE__'` ([apart from tests](https://github.com/doctrine/annotations/search?utf8=%E2%9C%93&q=__namespace__)) is set in the Doctrine/Annotations code base is [AnnotationReader.php#L389](https://github.com/doctrine/annotations/blob/master/lib/Doctrine/Common/Annotations/AnnotationReader.php#L389), where it seems that it's used to pass the class namespace. 

Since that part was sliced away in this project, and the class namespace is manually tested ([PhpDocReader.php#L243](https://github.com/PHP-DI/PhpDocReader/blob/master/src/PhpDocReader/PhpDocReader.php#L243)), I think it's dead code.

**Comment by mnapoli** [comment]
Right because we check `$class->getNamespaceName()` explicitly! Thanks for doing the research! I'm fine to merge a PR if you want to remove it?

**Comment by thebigb** [comment]
I'm working on #5, and came across this while refactoring. I'm aiming to have a pull request ready somewhere this weekend.
